# Removed version as it's obsolete in Docker Compose V2

services:
  skylink-nvr:
    build: 
      context: .
      target: production
    ports:
      - "8080:8080"
      - "5000:5000"
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./recordings:/app/recordings
      - ./snapshots:/app/snapshots
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://skylink:${POSTGRES_PASSWORD:-skylink_secure_pass}@postgres:5432/skylink_nvr
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - PORT=8080
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - skylink-network

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skylink_nvr
      - POSTGRES_USER=skylink
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-skylink_secure_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - ./init-schema.sql:/docker-entrypoint-initdb.d/init-schema.sql:ro
    ports:
      - "5432:5432"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skylink -d skylink_nvr"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - skylink-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - skylink-network

volumes:
  postgres_data:
  redis_data:

networks:
  skylink-network:
    driver: bridge