version: '3.8'

services:
  skylink-nvr:
    build: 
      context: .
      target: production
    network_mode: host
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - recordings_data:/app/recordings
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://skylink:${POSTGRES_PASSWORD:-skylink_secure_pass}@localhost:5432/skylink_nvr
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
      - RECORDINGS_PATH=/app/recordings
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=skylink_nvr
      - POSTGRES_USER=skylink
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-skylink_secure_pass}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  recordings_data: