version: '3.8'

services:
  skylink-nvr:
    build: .
    network_mode: host
    privileged: true
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - recordings_data:/app/recordings
      - ./uploads:/app/uploads
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgres://skylink:${POSTGRES_PASSWORD}@postgres:5432/skylink_nvr
      - HOST_PROC=/host/proc
      - HOST_SYS=/host/sys
    restart: unless-stopped
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=skylink_nvr
      - POSTGRES_USER=skylink
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  postgres_data:
  recordings_data: